
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Apr 10 2026 10:27:55 IST (Apr 10 2026 04:57:55 UTC)

// Verification Directory fv/mbist_top 

module mbist_top(clk, rst_n, bist_start, bist_done, bist_pass,
     mem_addr, mem_din, mem_dout, mem_we, mem_en);
  input clk, rst_n, bist_start;
  input [7:0] mem_dout;
  output bist_done, bist_pass, mem_we, mem_en;
  output [3:0] mem_addr;
  output [7:0] mem_din;
  wire clk, rst_n, bist_start;
  wire [7:0] mem_dout;
  wire bist_done, bist_pass, mem_we, mem_en;
  wire [3:0] mem_addr;
  wire [7:0] mem_din;
  wire [3:0] u_fsm_state;
  wire comp_error, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  assign mem_en = 1'b1;
  assign mem_din[0] = mem_din[7];
  assign mem_din[1] = mem_din[7];
  assign mem_din[2] = mem_din[7];
  assign mem_din[3] = mem_din[7];
  assign mem_din[4] = mem_din[7];
  assign mem_din[5] = mem_din[7];
  assign mem_din[6] = mem_din[7];
  DFFQX1 \u_addr_gen_addr_reg[3] (.CK (clk), .D (n_72), .Q
       (mem_addr[3]));
  DFFQX1 \u_addr_gen_addr_reg[2] (.CK (clk), .D (n_71), .Q
       (mem_addr[2]));
  DFFQX1 \u_addr_gen_addr_reg[1] (.CK (clk), .D (n_66), .Q
       (mem_addr[1]));
  DFFQX1 \u_addr_gen_addr_reg[0] (.CK (clk), .D (n_67), .Q
       (mem_addr[0]));
  DFFQX1 \u_fsm_state_reg[0] (.CK (clk), .D (n_65), .Q
       (u_fsm_state[0]));
  OAI221XL g2562__2398(.A0 (n_70), .A1 (n_18), .B0 (n_69), .B1 (n_63),
       .C0 (n_68), .Y (n_72));
  DFFQX1 u_fsm_bist_pass_reg(.CK (clk), .D (n_64), .Q (bist_pass));
  SDFFQX1 u_comparator_error_flag_reg(.CK (clk), .D (comp_error), .SI
       (rst_n), .SE (n_59), .Q (comp_error));
  OAI221XL g2572__5107(.A0 (n_70), .A1 (n_19), .B0 (n_69), .B1 (n_48),
       .C0 (n_68), .Y (n_71));
  OAI221XL g2573__6260(.A0 (n_70), .A1 (n_28), .B0 (n_69), .B1
       (mem_addr[0]), .C0 (n_68), .Y (n_67));
  OAI221XL g2574__4319(.A0 (n_70), .A1 (n_12), .B0 (n_69), .B1 (n_29),
       .C0 (n_68), .Y (n_66));
  OAI21X1 g2567__8428(.A0 (n_61), .A1 (n_57), .B0 (n_60), .Y (n_65));
  DFFQX1 \u_fsm_state_reg[1] (.CK (clk), .D (n_62), .Q
       (u_fsm_state[1]));
  DFFQX2 \u_fsm_state_reg[2] (.CK (clk), .D (n_58), .Q
       (u_fsm_state[2]));
  MXI2XL g2568__5526(.A (n_9), .B (comp_error), .S0 (n_56), .Y (n_64));
  AOI21XL g2576__6783(.A0 (n_53), .A1 (n_52), .B0 (n_54), .Y (n_63));
  OAI21XL g2570__3680(.A0 (n_50), .A1 (n_61), .B0 (n_60), .Y (n_62));
  OAI211X1 g2579__1617(.A0 (n_38), .A1 (n_27), .B0 (rst_n), .C0 (n_46),
       .Y (n_59));
  NAND3X1 g2583__2802(.A (rst_n), .B (n_51), .C (n_35), .Y (n_70));
  OAI21X1 g2575__1705(.A0 (n_61), .A1 (n_45), .B0 (n_60), .Y (n_58));
  AOI221X1 g2577__5122(.A0 (n_40), .A1 (n_49), .B0 (u_fsm_state[1]),
       .B1 (n_15), .C0 (n_43), .Y (n_57));
  AOI211X1 g2578__8246(.A0 (n_33), .A1 (n_42), .B0 (n_0), .C0
       (bist_done), .Y (n_56));
  NOR2XL g2580__7098(.A (n_53), .B (n_52), .Y (n_54));
  NAND3BX1 g2581__6131(.AN (n_51), .B (rst_n), .C (mem_din[7]), .Y
       (n_68));
  MXI2XL g2582__1881(.A (u_fsm_state[1]), .B (n_49), .S0 (n_41), .Y
       (n_50));
  INVXL g2584(.A (n_47), .Y (n_48));
  ADDFXL g2585__5115(.A (mem_addr[2]), .B (u_fsm_state[2]), .CI (n_22),
       .CO (n_52), .S (n_47));
  OAI31X1 g2586__7482(.A0 (mem_dout[7]), .A1 (n_31), .A2 (n_37), .B0
       (n_44), .Y (n_46));
  AOI21X1 g2587__4733(.A0 (n_44), .A1 (n_39), .B0 (u_fsm_state[2]), .Y
       (n_45));
  INVXL g2589(.A (n_42), .Y (n_43));
  AOI21X1 g2588__6161(.A0 (bist_start), .A1 (n_25), .B0 (n_41), .Y
       (n_51));
  OAI22X1 g2591__9315(.A0 (n_16), .A1 (n_39), .B0 (n_8), .B1
       (u_fsm_state[0]), .Y (n_40));
  OAI21X1 g2592__9945(.A0 (u_fsm_state[0]), .A1 (n_39), .B0 (n_11), .Y
       (n_42));
  NAND2XL g2593__2883(.A (rst_n), .B (n_61), .Y (n_60));
  NOR2XL g2590__2346(.A (n_37), .B (n_32), .Y (n_38));
  AND2X1 g2596__1666(.A (mem_we), .B (n_39), .Y (n_41));
  NAND2XL g2594__7410(.A (rst_n), .B (n_34), .Y (n_69));
  CLKINVX1 g2597(.A (n_34), .Y (n_35));
  OAI21X1 g2604__6417(.A0 (u_fsm_state[0]), .A1 (n_30), .B0 (n_26), .Y
       (n_44));
  NAND2XL g2599__5477(.A (rst_n), .B (n_33), .Y (n_61));
  NAND3BXL g2595__2398(.AN (n_31), .B (mem_dout[5]), .C (mem_dout[2]),
       .Y (n_32));
  OAI21X1 g2598__5107(.A0 (n_30), .A1 (bist_done), .B0 (n_23), .Y
       (n_34));
  MXI2XL g2600__6260(.A (n_28), .B (mem_addr[0]), .S0 (n_13), .Y
       (n_29));
  OAI2BB1X1 g2601__4319(.A0N (mem_dout[1]), .A1N (n_27), .B0 (n_24), .Y
       (n_37));
  OAI31X1 g2602__8428(.A0 (n_21), .A1 (u_fsm_state[2]), .A2 (n_10), .B0
       (n_20), .Y (n_39));
  CLKINVX1 g2610(.A (mem_din[7]), .Y (n_26));
  NAND2BX1 g2603__5526(.AN (n_25), .B (comp_error), .Y (n_33));
  AOI222XL g2607__6783(.A0 (mem_dout[0]), .A1 (n_5), .B0 (mem_dout[2]),
       .B1 (n_7), .C0 (n_2), .C1 (mem_dout[3]), .Y (n_24));
  INVXL g2609(.A (n_23), .Y (mem_we));
  OAI222XL g2608__3680(.A0 (mem_dout[4]), .A1 (n_1), .B0 (mem_dout[6]),
       .B1 (n_6), .C0 (n_3), .C1 (mem_dout[7]), .Y (n_31));
  OAI21X1 g2605__1617(.A0 (n_14), .A1 (n_17), .B0 (n_21), .Y (n_22));
  NAND4XL g2606__2802(.A (u_fsm_state[2]), .B (n_19), .C (n_18), .D
       (n_17), .Y (n_20));
  NOR2XL g2613__1705(.A (n_49), .B (n_16), .Y (mem_din[7]));
  AND2X1 g2611__5122(.A (n_49), .B (n_15), .Y (n_25));
  NAND2XL g2612__8246(.A (u_fsm_state[0]), .B (n_30), .Y (n_23));
  OAI22X1 g2614__7098(.A0 (mem_addr[3]), .A1 (u_fsm_state[2]), .B0
       (n_18), .B1 (n_14), .Y (n_53));
  OAI22X1 g2616__6131(.A0 (mem_addr[1]), .A1 (u_fsm_state[2]), .B0
       (n_12), .B1 (n_14), .Y (n_13));
  NAND3X1 g2615__1881(.A (u_fsm_state[0]), .B (n_49), .C
       (u_fsm_state[2]), .Y (n_27));
  NOR2XL g2617__5115(.A (n_4), .B (n_30), .Y (bist_done));
  INVXL g2622(.A (n_30), .Y (n_11));
  NAND2XL g2624__7482(.A (u_fsm_state[0]), .B (n_14), .Y (n_16));
  NAND2XL g2618__4733(.A (mem_addr[2]), .B (mem_addr[3]), .Y (n_10));
  NOR2XL g2621__6161(.A (mem_addr[0]), .B (mem_addr[1]), .Y (n_17));
  NAND2XL g2625__9315(.A (mem_addr[0]), .B (mem_addr[1]), .Y (n_21));
  NAND2XL g2620__9945(.A (rst_n), .B (bist_pass), .Y (n_9));
  NOR2XL g2619__2883(.A (bist_start), .B (u_fsm_state[2]), .Y (n_8));
  NOR2XL g2623__2346(.A (u_fsm_state[0]), .B (u_fsm_state[2]), .Y
       (n_15));
  NAND2XL g2626__1666(.A (u_fsm_state[1]), .B (u_fsm_state[2]), .Y
       (n_30));
  INVXL g2637(.A (mem_dout[3]), .Y (n_7));
  INVXL g2635(.A (mem_dout[5]), .Y (n_6));
  INVXL g2636(.A (mem_dout[1]), .Y (n_5));
  INVXL g2631(.A (u_fsm_state[0]), .Y (n_4));
  CLKINVX1 g2638(.A (mem_addr[2]), .Y (n_19));
  CLKINVX1 g2628(.A (mem_addr[3]), .Y (n_18));
  CLKINVX1 g2632(.A (u_fsm_state[1]), .Y (n_49));
  INVXL g2627(.A (mem_dout[4]), .Y (n_3));
  INVXL g2634(.A (mem_dout[0]), .Y (n_2));
  INVXL g2633(.A (mem_dout[6]), .Y (n_1));
  INVXL g2639(.A (rst_n), .Y (n_0));
  CLKINVX1 g2629(.A (mem_addr[1]), .Y (n_12));
  CLKINVX1 g2630(.A (mem_addr[0]), .Y (n_28));
  CLKINVX1 g2640(.A (u_fsm_state[2]), .Y (n_14));
endmodule

