
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Apr 10 2026 10:27:39 IST (Apr 10 2026 04:57:39 UTC)

// Verification Directory fv/mbist_top 

module mbist_top(clk, rst_n, bist_start, bist_done, bist_pass,
     mem_addr, mem_din, mem_dout, mem_we, mem_en);
  input clk, rst_n, bist_start;
  input [7:0] mem_dout;
  output bist_done, bist_pass, mem_we, mem_en;
  output [3:0] mem_addr;
  output [7:0] mem_din;
  wire clk, rst_n, bist_start;
  wire [7:0] mem_dout;
  wire bist_done, bist_pass, mem_we, mem_en;
  wire [3:0] mem_addr;
  wire [7:0] mem_din;
  wire [3:0] u_fsm_state;
  wire comp_error, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_30, n_31;
  wire n_32, n_33, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_97, n_98, n_99, n_100, n_101, n_102, n_103, n_104;
  wire n_105, n_106;
  assign mem_en = 1'b1;
  assign mem_din[0] = mem_din[7];
  assign mem_din[1] = mem_din[7];
  assign mem_din[2] = mem_din[7];
  assign mem_din[3] = mem_din[7];
  assign mem_din[4] = mem_din[7];
  assign mem_din[5] = mem_din[7];
  assign mem_din[6] = mem_din[7];
  DFFQX1 \u_addr_gen_addr_reg[3] (.CK (clk), .D (n_106), .Q
       (mem_addr[3]));
  DFFQX1 \u_addr_gen_addr_reg[2] (.CK (clk), .D (n_105), .Q
       (mem_addr[2]));
  DFFQX1 \u_addr_gen_addr_reg[1] (.CK (clk), .D (n_104), .Q
       (mem_addr[1]));
  DFFQX1 \u_fsm_state_reg[0] (.CK (clk), .D (n_102), .Q
       (u_fsm_state[0]));
  OAI211XL g4207__2398(.A0 (n_93), .A1 (mem_addr[3]), .B0 (n_103), .C0
       (n_97), .Y (n_106));
  DFFQX1 \u_addr_gen_addr_reg[0] (.CK (clk), .D (n_98), .Q
       (mem_addr[0]));
  DFFQX1 \u_fsm_state_reg[2] (.CK (clk), .D (n_101), .Q
       (u_fsm_state[2]));
  CLKINVX1 g4206(.A (n_99), .Y (n_105));
  OAI211XL g4215__5107(.A0 (n_87), .A1 (n_90), .B0 (n_103), .C0 (n_89),
       .Y (n_104));
  OAI21XL g4208__6260(.A0 (n_100), .A1 (n_85), .B0 (n_94), .Y (n_102));
  DFFQX1 \u_fsm_state_reg[3] (.CK (clk), .D (n_95), .Q
       (u_fsm_state[3]));
  DFFQX1 u_comparator_error_flag_reg(.CK (clk), .D (n_96), .Q
       (comp_error));
  OAI32X1 g4225__4319(.A0 (n_100), .A1 (n_40), .A2 (n_57), .B0 (n_83),
       .B1 (comp_error), .Y (n_101));
  AOI211XL g4209__8428(.A0 (n_84), .A1 (mem_addr[2]), .B0 (n_92), .C0
       (n_79), .Y (n_99));
  OAI211XL g4217__5526(.A0 (mem_addr[0]), .A1 (n_82), .B0 (n_103), .C0
       (n_70), .Y (n_98));
  DFFQX1 \u_fsm_state_reg[1] (.CK (clk), .D (n_91), .Q
       (u_fsm_state[1]));
  OAI31XL g4211__6783(.A0 (n_75), .A1 (n_88), .A2 (n_47), .B0
       (mem_addr[3]), .Y (n_97));
  NOR2XL g4212__3680(.A (n_3), .B (n_78), .Y (n_96));
  OAI222XL g4216__1617(.A0 (n_24), .A1 (n_26), .B0 (n_100), .B1 (n_77),
       .C0 (n_59), .C1 (n_19), .Y (n_95));
  AOI221X1 g4218__2802(.A0 (n_72), .A1 (n_51), .B0 (n_76), .B1 (n_60),
       .C0 (n_71), .Y (n_94));
  DFFQX1 u_fsm_bist_pass_reg(.CK (clk), .D (n_86), .Q (bist_pass));
  AOI21XL g4229__1705(.A0 (n_80), .A1 (n_46), .B0 (n_92), .Y (n_93));
  OAI211XL g4231__5122(.A0 (n_90), .A1 (n_58), .B0 (n_73), .C0 (n_66),
       .Y (n_91));
  AOI22XL g4220__8246(.A0 (mem_addr[1]), .A1 (n_88), .B0 (n_87), .B1
       (n_81), .Y (n_89));
  OAI32X1 g4222__7098(.A0 (n_100), .A1 (n_13), .A2 (n_65), .B0 (n_61),
       .B1 (n_1), .Y (n_86));
  MXI2XL g4223__6131(.A (n_49), .B (n_62), .S0 (u_fsm_state[1]), .Y
       (n_85));
  OAI21X1 g4224__1881(.A0 (n_74), .A1 (n_11), .B0 (n_69), .Y (n_84));
  AOI21XL g4241__5115(.A0 (n_16), .A1 (n_56), .B0 (n_67), .Y (n_83));
  NOR2XL g4234__7482(.A (n_81), .B (n_80), .Y (n_82));
  OAI31XL g4233__4733(.A0 (mem_addr[2]), .A1 (n_90), .A2 (n_68), .B0
       (n_103), .Y (n_79));
  AOI21X1 g4219__6161(.A0 (n_54), .A1 (n_64), .B0 (comp_error), .Y
       (n_78));
  NOR2XL g4227__9315(.A (comp_error), .B (n_63), .Y (n_77));
  OAI211X1 g4230__9945(.A0 (n_55), .A1 (n_48), .B0 (n_31), .C0 (n_52),
       .Y (n_76));
  NOR2XL g4232__2883(.A (n_74), .B (n_37), .Y (n_75));
  NOR2XL g4235__2346(.A (n_74), .B (n_17), .Y (n_92));
  AOI211X1 g4247__1666(.A0 (n_72), .A1 (u_fsm_state[2]), .B0 (n_44),
       .C0 (n_71), .Y (n_73));
  CLKINVX1 g4246(.A (n_74), .Y (n_81));
  NAND3X1 g4249__7410(.A (rst_n), .B (n_53), .C (n_45), .Y (n_103));
  NAND2XL g4226__6417(.A (n_88), .B (mem_addr[0]), .Y (n_70));
  AOI21X1 g4228__5477(.A0 (n_80), .A1 (n_68), .B0 (n_88), .Y (n_69));
  NOR2XL g4243__2398(.A (n_66), .B (n_65), .Y (n_67));
  NAND4XL g4248__5107(.A (n_39), .B (n_28), .C (n_20), .D (n_36), .Y
       (n_64));
  AOI21XL g4238__6260(.A0 (n_35), .A1 (n_65), .B0 (n_38), .Y (n_63));
  NAND3X1 g4250__4319(.A (rst_n), .B (n_18), .C (n_50), .Y (n_74));
  OAI21X1 g4239__8428(.A0 (u_fsm_state[2]), .A1 (n_65), .B0 (n_43), .Y
       (n_62));
  AOI22X1 g4240__5526(.A0 (rst_n), .A1 (n_41), .B0 (n_60), .B1 (n_59),
       .Y (n_61));
  INVXL g4242(.A (n_57), .Y (n_58));
  OAI21XL g4259__6783(.A0 (u_fsm_state[0]), .A1 (n_55), .B0 (n_42), .Y
       (n_56));
  NAND2XL g4255__3680(.A (n_80), .B (u_fsm_state[2]), .Y (n_66));
  NAND2XL g4245__1617(.A (n_25), .B (n_65), .Y (n_57));
  OAI211XL g4237__2802(.A0 (n_7), .A1 (n_53), .B0 (n_30), .C0 (n_27),
       .Y (n_54));
  NAND2XL g4244__1705(.A (n_51), .B (n_65), .Y (n_52));
  AOI21X1 g4236__5122(.A0 (n_100), .A1 (n_32), .B0 (n_50), .Y (n_88));
  INVXL g4251(.A (n_48), .Y (n_49));
  NOR2XL g4252__8246(.A (n_90), .B (n_46), .Y (n_47));
  INVXL g4257(.A (n_65), .Y (n_45));
  AOI21X1 g4260__7098(.A0 (n_43), .A1 (n_33), .B0 (n_100), .Y (n_44));
  INVXL g4264(.A (n_42), .Y (mem_din[7]));
  OAI21X1 g4258__6131(.A0 (n_100), .A1 (n_14), .B0 (comp_error), .Y
       (n_41));
  OAI211X1 g4261__1881(.A0 (u_fsm_state[1]), .A1 (n_15), .B0 (n_40),
       .C0 (n_39), .Y (n_50));
  NOR2XL g4256__5115(.A (comp_error), .B (n_23), .Y (n_48));
  AOI32X1 g4262__7482(.A0 (mem_addr[3]), .A1 (n_38), .A2 (n_46), .B0
       (n_37), .B1 (n_12), .Y (n_65));
  NAND2XL g4265__4733(.A (u_fsm_state[3]), .B (n_35), .Y (n_36));
  NOR2XL g4266__6161(.A (n_5), .B (n_33), .Y (bist_done));
  NAND2XL g4269__9315(.A (u_fsm_state[1]), .B (n_22), .Y (n_42));
  CLKINVX1 g4263(.A (n_90), .Y (n_80));
  OAI21X1 g4253__9945(.A0 (n_31), .A1 (u_fsm_state[1]), .B0 (rst_n), .Y
       (n_32));
  NAND2XL g4254__2883(.A (n_6), .B (n_53), .Y (n_30));
  NAND2XL g4267__2346(.A (n_21), .B (n_28), .Y (mem_we));
  AOI221XL g4274__1666(.A0 (mem_dout[3]), .A1 (n_9), .B0 (mem_dout[7]),
       .B1 (n_8), .C0 (n_10), .Y (n_27));
  NOR2XL g4270__7410(.A (comp_error), .B (n_53), .Y (n_26));
  AOI21X1 g4275__6417(.A0 (u_fsm_state[0]), .A1 (n_25), .B0 (n_24), .Y
       (n_71));
  NAND2XL g4268__5477(.A (n_60), .B (u_fsm_state[0]), .Y (n_90));
  AOI21XL g4271__2398(.A0 (u_fsm_state[3]), .A1 (n_38), .B0
       (u_fsm_state[0]), .Y (n_23));
  INVXL g4276(.A (n_21), .Y (n_22));
  INVXL g4278(.A (n_53), .Y (n_20));
  CLKINVX1 g4288(.A (n_19), .Y (n_72));
  CLKINVX1 g4289(.A (n_40), .Y (n_35));
  NAND2XL g4296__5107(.A (u_fsm_state[1]), .B (n_18), .Y (n_33));
  CLKINVX1 g4277(.A (n_17), .Y (n_37));
  NAND2XL g4297__6260(.A (n_16), .B (comp_error), .Y (n_19));
  NAND2XL g4282__4319(.A (n_4), .B (n_51), .Y (n_21));
  NOR2XL g4283__8428(.A (comp_error), .B (n_51), .Y (n_43));
  NOR2BX1 g4285__5526(.AN (n_16), .B (u_fsm_state[1]), .Y (n_60));
  NOR2XL g4287__6783(.A (n_55), .B (n_15), .Y (n_53));
  NAND2XL g4292__3680(.A (u_fsm_state[1]), .B (n_51), .Y (n_14));
  NAND3X1 g4291__1617(.A (u_fsm_state[1]), .B (n_59), .C (n_25), .Y
       (n_13));
  NOR2XL g4279__2802(.A (mem_addr[3]), .B (n_38), .Y (n_12));
  NAND2XL g4294__1705(.A (n_16), .B (u_fsm_state[1]), .Y (n_24));
  NAND3X1 g4295__5122(.A (u_fsm_state[1]), .B (u_fsm_state[3]), .C
       (n_59), .Y (n_39));
  NAND2BX1 g4293__8246(.AN (n_15), .B (u_fsm_state[1]), .Y (n_28));
  NAND2XL g4298__7098(.A (n_0), .B (n_51), .Y (n_40));
  NAND2BXL g4280__6131(.AN (n_11), .B (n_68), .Y (n_87));
  NAND2XL g4281__1881(.A (bist_start), .B (n_59), .Y (n_31));
  NAND2XL g4284__5115(.A (n_2), .B (n_11), .Y (n_17));
  OAI22XL g4290__7482(.A0 (n_9), .A1 (mem_dout[2]), .B0 (n_8), .B1
       (mem_dout[6]), .Y (n_10));
  CLKINVX1 g4303(.A (n_38), .Y (n_18));
  NOR2BX1 g4286__4733(.AN (mem_addr[2]), .B (n_68), .Y (n_46));
  NOR4XL g4272__6161(.A (mem_dout[4]), .B (mem_dout[6]), .C
       (mem_dout[2]), .D (mem_dout[0]), .Y (n_7));
  NAND4XL g4273__9315(.A (mem_dout[4]), .B (mem_dout[7]), .C
       (mem_dout[3]), .D (mem_dout[0]), .Y (n_6));
  NOR2X1 g4306__9945(.A (u_fsm_state[2]), .B (n_5), .Y (n_51));
  NAND2XL g4304__2883(.A (u_fsm_state[0]), .B (n_4), .Y (n_15));
  NOR2XL g4305__2346(.A (n_3), .B (u_fsm_state[3]), .Y (n_16));
  NAND2X1 g4307__1666(.A (u_fsm_state[3]), .B (n_55), .Y (n_38));
  NOR2XL g4299__7410(.A (mem_addr[0]), .B (mem_addr[1]), .Y (n_11));
  NOR2X1 g4301__6417(.A (u_fsm_state[0]), .B (u_fsm_state[2]), .Y
       (n_59));
  NAND2X1 g4300__5477(.A (mem_addr[0]), .B (mem_addr[1]), .Y (n_68));
  NAND2XL g4302__2398(.A (rst_n), .B (u_fsm_state[3]), .Y (n_100));
  INVXL g4313(.A (mem_addr[2]), .Y (n_2));
  CLKINVX1 g4312(.A (bist_pass), .Y (n_1));
  INVXL g4317(.A (u_fsm_state[1]), .Y (n_0));
  CLKINVX1 g4309(.A (u_fsm_state[3]), .Y (n_4));
  CLKINVX1 g4316(.A (u_fsm_state[2]), .Y (n_55));
  INVXL g4308(.A (mem_dout[1]), .Y (n_9));
  INVXL g4314(.A (rst_n), .Y (n_3));
  INVXL g4311(.A (mem_dout[5]), .Y (n_8));
  CLKINVX1 g4315(.A (u_fsm_state[0]), .Y (n_5));
  CLKINVX1 g4310(.A (comp_error), .Y (n_25));
endmodule

