
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Apr 10 2026 10:28:17 IST (Apr 10 2026 04:58:17 UTC)

// Verification Directory fv/mbist_top 

module mbist_top(clk, rst_n, bist_start, bist_done, bist_pass,
     mem_addr, mem_din, mem_dout, mem_we, mem_en);
  input clk, rst_n, bist_start;
  input [7:0] mem_dout;
  output bist_done, bist_pass, mem_we, mem_en;
  output [3:0] mem_addr;
  output [7:0] mem_din;
  wire clk, rst_n, bist_start;
  wire [7:0] mem_dout;
  wire bist_done, bist_pass, mem_we, mem_en;
  wire [3:0] mem_addr;
  wire [7:0] mem_din;
  wire [3:0] u_fsm_state;
  wire comp_error, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83;
  assign mem_en = 1'b1;
  assign mem_din[0] = mem_din[7];
  assign mem_din[1] = mem_din[7];
  assign mem_din[2] = mem_din[7];
  assign mem_din[3] = mem_din[7];
  assign mem_din[4] = mem_din[7];
  assign mem_din[5] = mem_din[7];
  assign mem_din[6] = mem_din[7];
  DFFQX1 u_fsm_bist_pass_reg(.CK (clk), .D (n_83), .Q (bist_pass));
  DFFQXL \u_addr_gen_addr_reg[2] (.CK (clk), .D (n_82), .Q
       (mem_addr[2]));
  MXI2XL g2859__2398(.A (n_5), .B (comp_error), .S0 (n_75), .Y (n_83));
  DFFQX1 \u_addr_gen_addr_reg[3] (.CK (clk), .D (n_76), .Q
       (mem_addr[3]));
  DFFQX1 \u_addr_gen_addr_reg[1] (.CK (clk), .D (n_81), .Q
       (mem_addr[1]));
  DFFQX1 \u_addr_gen_addr_reg[0] (.CK (clk), .D (n_78), .Q
       (mem_addr[0]));
  OAI211XL g2874__5107(.A0 (n_27), .A1 (n_80), .B0 (n_79), .C0 (n_73),
       .Y (n_82));
  OAI221XL g2871__6260(.A0 (n_80), .A1 (n_31), .B0 (n_77), .B1 (n_41),
       .C0 (n_79), .Y (n_81));
  OAI221XL g2872__4319(.A0 (n_80), .A1 (n_40), .B0 (n_77), .B1
       (mem_addr[0]), .C0 (n_79), .Y (n_78));
  OAI221XL g2860__8428(.A0 (n_80), .A1 (n_34), .B0 (n_77), .B1 (n_67),
       .C0 (n_79), .Y (n_76));
  DFFQX2 \u_fsm_state_reg[2] (.CK (clk), .D (n_71), .Q
       (u_fsm_state[2]));
  DFFQX2 \u_fsm_state_reg[1] (.CK (clk), .D (n_72), .Q
       (u_fsm_state[1]));
  AOI211X1 g2864__5526(.A0 (n_25), .A1 (n_65), .B0 (n_63), .C0
       (bist_done), .Y (n_75));
  DFFQX1 \u_fsm_state_reg[0] (.CK (clk), .D (n_69), .Q
       (u_fsm_state[0]));
  NAND2BXL g2879__6783(.AN (n_77), .B (n_49), .Y (n_73));
  DFFQX2 \u_fsm_state_reg[3] (.CK (clk), .D (n_64), .Q
       (u_fsm_state[3]));
  OAI21XL g2873__3680(.A0 (n_61), .A1 (n_70), .B0 (n_68), .Y (n_72));
  NOR2XL g2876__1617(.A (n_70), .B (n_66), .Y (n_71));
  OAI21XL g2867__2802(.A0 (n_55), .A1 (n_70), .B0 (n_68), .Y (n_69));
  AOI21XL g2878__1705(.A0 (n_57), .A1 (n_56), .B0 (n_58), .Y (n_67));
  AOI33XL g2883__5122(.A0 (n_44), .A1 (n_0), .A2 (n_51), .B0
       (u_fsm_state[2]), .B1 (n_54), .B2 (n_48), .Y (n_66));
  NAND3X1 g2887__8246(.A (rst_n), .B (n_62), .C (u_fsm_state[2]), .Y
       (n_79));
  NAND2XL g2875__7098(.A (n_53), .B (n_60), .Y (n_65));
  OAI21XL g2877__6131(.A0 (n_70), .A1 (n_52), .B0 (n_68), .Y (n_64));
  OR3X1 g2889__1881(.A (n_63), .B (n_62), .C (n_59), .Y (n_77));
  INVXL g2881(.A (n_60), .Y (n_61));
  SDFFQX1 u_comparator_error_flag_reg(.CK (clk), .D (comp_error), .SI
       (rst_n), .SE (n_46), .Q (comp_error));
  NAND3X1 g2890__5115(.A (rst_n), .B (n_50), .C (n_59), .Y (n_80));
  NOR2XL g2880__7482(.A (n_57), .B (n_56), .Y (n_58));
  AOI21X1 g2882__4733(.A0 (n_42), .A1 (n_54), .B0 (n_53), .Y (n_55));
  OAI211X1 g2884__6161(.A0 (u_fsm_state[1]), .A1 (n_43), .B0 (n_47),
       .C0 (n_45), .Y (n_60));
  AOI21X1 g2888__9315(.A0 (n_15), .A1 (n_51), .B0 (n_9), .Y (n_52));
  CLKINVX1 g2891(.A (n_50), .Y (n_62));
  ADDFXL g2885__9945(.A (mem_addr[2]), .B (n_35), .CI (n_33), .CO
       (n_56), .S (n_49));
  NAND2XL g2892__2883(.A (u_fsm_state[1]), .B (n_51), .Y (n_48));
  AOI21X1 g2894__2346(.A0 (bist_start), .A1 (n_20), .B0 (n_51), .Y
       (n_50));
  OAI221X1 g2897__1666(.A0 (n_47), .A1 (n_36), .B0 (u_fsm_state[0]),
       .B1 (n_19), .C0 (n_21), .Y (n_53));
  OAI21X1 g2886__7410(.A0 (n_37), .A1 (n_24), .B0 (rst_n), .Y (n_46));
  NAND2XL g2893__6417(.A (n_44), .B (n_43), .Y (n_45));
  OAI32X1 g2895__5477(.A0 (n_16), .A1 (n_18), .A2 (n_38), .B0 (n_10),
       .B1 (u_fsm_state[0]), .Y (n_42));
  CLKINVX1 g2898(.A (n_43), .Y (n_51));
  MXI2XL g2896__2398(.A (n_40), .B (mem_addr[0]), .S0 (n_30), .Y
       (n_41));
  NAND2XL g2899__5107(.A (mem_we), .B (n_38), .Y (n_43));
  AOI211X1 g2900__6260(.A0 (mem_dout[5]), .A1 (u_fsm_state[1]), .B0
       (n_6), .C0 (n_29), .Y (n_37));
  INVXL g2901(.A (n_38), .Y (n_36));
  NAND2XL g2911__4319(.A (rst_n), .B (n_70), .Y (n_68));
  OAI21X1 g2902__8428(.A0 (n_7), .A1 (n_35), .B0 (n_28), .Y (n_38));
  OAI22X1 g2905__5526(.A0 (mem_addr[3]), .A1 (n_35), .B0 (n_34), .B1
       (n_32), .Y (n_57));
  OAI22X1 g2903__6783(.A0 (n_26), .A1 (n_32), .B0 (n_40), .B1 (n_31),
       .Y (n_33));
  OAI22X1 g2904__3680(.A0 (mem_addr[1]), .A1 (n_35), .B0 (n_31), .B1
       (n_32), .Y (n_30));
  OAI221XL g2907__1617(.A0 (mem_dout[1]), .A1 (n_2), .B0 (mem_dout[0]),
       .B1 (n_4), .C0 (n_22), .Y (n_29));
  NAND4XL g2908__2802(.A (n_27), .B (n_34), .C (n_26), .D (n_35), .Y
       (n_28));
  NAND2XL g2914__1705(.A (rst_n), .B (n_25), .Y (n_70));
  AOI21XL g2906__5122(.A0 (u_fsm_state[0]), .A1 (n_17), .B0 (n_23), .Y
       (n_24));
  NOR2XL g2912__8246(.A (mem_we), .B (n_23), .Y (n_59));
  AOI221XL g2913__7098(.A0 (mem_dout[1]), .A1 (n_12), .B0
       (mem_dout[4]), .B1 (n_11), .C0 (n_13), .Y (n_22));
  CLKINVX1 g2909(.A (n_35), .Y (n_32));
  INVXL g2915(.A (bist_done), .Y (n_21));
  NAND2BX1 g2916__6131(.AN (n_20), .B (comp_error), .Y (n_25));
  NAND2X2 g2910__1881(.A (n_14), .B (n_19), .Y (n_35));
  NOR2XL g2917__5115(.A (u_fsm_state[0]), .B (n_47), .Y (n_23));
  NOR2XL g2918__7482(.A (n_18), .B (n_47), .Y (bist_done));
  OAI21X1 g2919__4733(.A0 (u_fsm_state[3]), .A1 (n_8), .B0 (n_19), .Y
       (n_17));
  AOI21X1 g2921__6161(.A0 (u_fsm_state[3]), .A1 (n_16), .B0 (n_18), .Y
       (mem_we));
  INVXL g2925(.A (n_14), .Y (n_15));
  NOR3X1 g2927__9315(.A (u_fsm_state[3]), .B (u_fsm_state[0]), .C
       (n_16), .Y (n_20));
  OAI222XL g2920__9945(.A0 (mem_dout[3]), .A1 (n_3), .B0 (mem_dout[4]),
       .B1 (n_12), .C0 (n_11), .C1 (mem_dout[5]), .Y (n_13));
  NOR2XL g2922__2883(.A (bist_start), .B (n_16), .Y (n_10));
  NAND2X1 g2928__2346(.A (u_fsm_state[2]), .B (n_44), .Y (n_14));
  NAND2XL g2924__1666(.A (u_fsm_state[1]), .B (n_9), .Y (n_47));
  NOR2BXL g2929__7410(.AN (n_44), .B (n_18), .Y (mem_din[7]));
  NAND2X2 g2923__6417(.A (u_fsm_state[3]), .B (n_8), .Y (n_19));
  NAND4XL g2926__5477(.A (mem_addr[1]), .B (mem_addr[0]), .C
       (mem_addr[2]), .D (mem_addr[3]), .Y (n_7));
  NOR2XL g2935__2398(.A (u_fsm_state[2]), .B (n_54), .Y (n_9));
  CLKINVX1 g2930(.A (n_8), .Y (n_16));
  NOR2X2 g2936__5107(.A (u_fsm_state[3]), .B (n_1), .Y (n_44));
  NOR2XL g2931__6260(.A (mem_dout[2]), .B (u_fsm_state[1]), .Y (n_6));
  NOR2XL g2932__4319(.A (mem_addr[0]), .B (mem_addr[1]), .Y (n_26));
  NAND2XL g2934__8428(.A (rst_n), .B (bist_pass), .Y (n_5));
  NOR2X2 g2933__5526(.A (u_fsm_state[2]), .B (u_fsm_state[1]), .Y
       (n_8));
  INVXL g2937(.A (mem_dout[3]), .Y (n_4));
  INVXL g2938(.A (mem_dout[2]), .Y (n_3));
  INVXL g2944(.A (mem_dout[0]), .Y (n_2));
  INVXL g2943(.A (mem_dout[7]), .Y (n_11));
  CLKINVX1 g2939(.A (mem_addr[3]), .Y (n_34));
  CLKINVX1 g2947(.A (mem_addr[1]), .Y (n_31));
  CLKINVX1 g2942(.A (u_fsm_state[0]), .Y (n_18));
  CLKINVX1 g2948(.A (u_fsm_state[1]), .Y (n_1));
  INVXL g2940(.A (u_fsm_state[2]), .Y (n_0));
  CLKINVX1 g2946(.A (mem_addr[2]), .Y (n_27));
  INVXL g2950(.A (rst_n), .Y (n_63));
  INVXL g2945(.A (mem_dout[6]), .Y (n_12));
  CLKINVX1 g2949(.A (mem_addr[0]), .Y (n_40));
  CLKINVX1 g2941(.A (u_fsm_state[3]), .Y (n_54));
endmodule

